{
 "title": "SUSE CaaS Platform Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "masters",
    "label": "Masters",
    "query": "label_values(kube_node_spec_taint{effect=\"NoSchedule\",key=\"node-role.kubernetes.io/master\"}, node)"
   },
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Masters Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\"$masters\"}) % sum(kube_node_status_condition{condition=\"Ready\", node=~\"$masters\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Workers Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_node_info{node!~\"$masters\"}) % sum(kube_node_status_condition{condition=\"Ready\", node!~\"$masters\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Working Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace!=\"\"})"
    }
   ]
  },
  {
   "title": "Workers Allocatable Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node!~\"$masters\"})"
    }
   ]
  },
  {
   "title": "Working CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Workers Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node!~\"$masters\"})"
    }
   ]
  },
  {
   "title": "Pods Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(kube_pod_container_info{namespace!=\"\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Workers Allocatable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node!~\"$masters\"})"
    }
   ]
  },
  {
   "title": "Masters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\"$masters\"})"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_node_info{node!~\"$masters\"})"
    }
   ]
  },
  {
   "title": "Memory Usage / Workers Allocatable Mem",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace!=\"\"}) / sum(kube_node_status_allocatable_memory_bytes{node!~\"$masters\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores Usage / Workers Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace!=\"\"}[5m])) / sum(kube_node_status_allocatable_cpu_cores{node!~\"$masters\"})) * 100"
    }
   ]
  },
  {
   "title": "Pods Number / Workers Allocatable Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace!=\"\"}) / sum(kube_node_status_allocatable_pods{node!~\"$masters\"}) * 100"
    }
   ]
  },
  {
   "title": "Masters Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node=~\"$masters\", status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", node=~\"$masters\", status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$masters\", status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", node=~\"$masters\", status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Workers Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node!~\"$masters\", status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", node!~\"$masters\", status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node!~\"$masters\", status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", node!~\"$masters\", status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_namespace_labels)" }
   ]
  },
  {
   "title": "VolumeClaims",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info)"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info)"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_daemonset_labels{namespace!=\"\"})",
     "legendFormat": "DaemonSets"
    },
    {
     "expr": "count(kube_deployment_labels{namespace!=\"\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "count(kube_replicaset_status_fully_labeled_replicas{namespace!=\"\"})",
     "legendFormat": "ReplicaSets"
    },
    {
     "expr": "count(kube_replicationcontroller_status_fully_labeled_replicas{namespace!=\"\"})",
     "legendFormat": "ReplicationControllers"
    },
    {
     "expr": "count(kube_statefulset_labels{namespace!=\"\"})",
     "legendFormat": "StatefulSets"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace!=\"\"}) by (container_name)"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace!=\"\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace!=\"\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace!=\"\", phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace!=\"\", phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace!=\"\", phase=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "ConfigMaps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_configmap_info)" }
   ]
  },
  {
   "title": "Secrets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_secret_info)" }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_service_info)" }
   ]
  },
  {
   "title": "Images",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(kube_pod_container_info{namespace!=\"\"}) by (image_id))"
    }
   ]
  },
  {
   "title": "NODES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "targets": [
      { "expr": "avg(kube_node_info) by(node)" },
      {
       "expr": "sum(kube_node_spec_taint{effect=\"NoSchedule\",key=\"node-role.kubernetes.io/master\"}) by (node)"
      },
      {
       "expr": "avg(kube_node_info) by(container_runtime_version, kernel_version, kubelet_version, kubelet_version, os_image)"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=~\"DiskPressure\", status=\"true\"}) by (node)"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=~\"MemoryPressure\", status=\"true\"}) by (node)"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=~\"OutOfDisk\", status=\"true\"}) by (node)"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=~\"Ready\", status=\"true\"}) by (node)"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKLOADS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workloads",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(kube_pod_owner{namespace!=\"\", owner_kind!=\"<none>\"}) by (namespace, owner_name, owner_kind)"
      }
     ]
    }
   ]
  },
  {
   "title": "PODS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{namespace!=\"\"}) by (namespace, pod)"
      },
      {
       "expr": "sum(kube_pod_container_info{namespace!=\"\"}) by (namespace, pod, container, image)"
      }
     ]
    }
   ]
  },
  {
   "title": "VOLUMES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace!=\"\"}) by (namespace, persistentvolumeclaim)"
      },
      {
       "expr": "count(kube_persistentvolumeclaim_info{namespace!=\"\"}) by (namespace, persistentvolumeclaim, volumename, storageclass)"
      },
      {
       "expr": "sum(kube_pod_spec_volumes_persistentvolumeclaims_readonly{namespace!=\"\"}) by (namespace, persistentvolumeclaim)"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace!=\"\"}) by (namespace, persistentvolumeclaim)"
      }
     ]
    }
   ]
  },
  {
   "title": "NAMESPACES MEMORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Working Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace!=\"\", container_name!=\"POD\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NAMESPACES CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace!=\"\", container_name!=\"POD\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NAMESPACES DISK I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS Read",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_total{namespace!=\"\", device=~\"(/dev/(sd|vd).*)\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Throughput Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_bytes_total{namespace!=\"\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "IOPS Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_read_seconds_total{namespace!=\"\", device=~\"(/dev/(sd|vd).*)\"} / container_fs_reads_total{namespace!=\"\", device=~\"(/dev/(sd|vd).*)\"}) by (device, namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "IOPS Write",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_total{namespace!=\"\", device=~\"(/dev/(sd|vd).*)\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Throughput Write",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_bytes_total{namespace!=\"\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "IOPS Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_write_seconds_total{namespace!=\"\", device=~\"(/dev/(sd|vd).*)\"} / container_fs_writes_total{namespace!=\"\", device=~\"(/dev/(sd|vd).*)\"}) by (device, namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NAMESPACES NETWORK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace!=\"\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Transmit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace!=\"\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}