{
 "title": "Apache2",
 "description": "Apache2 simple dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(apache_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host: $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "Apache Up / Down",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(apache_up{instance=~\"$hostname\"} == 1)",
     "legendFormat": "Apache Up"
    },
    {
     "expr": "count(apache_up{instance=~\"$hostname\"} == 0)",
     "legendFormat": "Apache Down"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_scoreboard{instance=~\"$hostname\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_workers{instance=~\"$hostname\"}\n",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_cpuload{instance=~\"$hostname\"}",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}