{
 "title": "Uyuni Client Systems",
 "description": "Uyuni Client Systems",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(up{job='mgr-clients', instance=~'.*'} , hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ALERTS", "labelSelector": "alertname, description", "target": "Query", "type": "table" }
   ]
  },
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "hostname" },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{hostname=~\"$hostname\", exporter=\"node_exporter\",  mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{hostname=~\"$hostname\", exporter=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{hostname=~\"$hostname\", exporter=\"node_exporter\", mode !=\"idle\"}[5m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{hostname=~\"$hostname\", exporter=\"node_exporter\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{hostname=~\"$hostname\", exporter=\"node_exporter\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{hostname=~\"$hostname\", exporter=\"node_exporter\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Ram",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=~\"$hostname\", exporter=\"node_exporter\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{hostname=~\"$hostname\", exporter=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{hostname=~\"$hostname\", exporter=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{hostname=~\"$hostname\", exporter=\"node_exporter\"} / node_memory_MemTotal_bytes)",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{hostname=~\"$hostname\", exporter=\"node_exporter\"} / node_filesystem_size_bytes",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "mount points",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{hostname=~\"$hostname\", exporter=\"node_exporter\"}+0"
    },
    {
     "expr": "node_filesystem_size_bytes{hostname=~\"$hostname\", exporter=\"node_exporter\"}"
    }
   ]
  }
 ]
}