{
 "title": "PostgreSQL database insights",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "Host", "query": { "query": "label_values(pg_up, instance)" } }
  ]
 },
 "panels": [
  { "title": "Database Server: $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "Fetches",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg (irate(pg_stat_database_tup_fetched{instance=~\"$hostname\"}[5m])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(irate(pg_stat_database_tup_inserted{instance=~\"$hostname\"}[5m])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(irate(pg_stat_database_tup_updated{instance=~\"$hostname\"}[5m])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(irate(pg_stat_database_tup_deleted{instance=~\"$hostname\"}[5m])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{instance=~\"$hostname\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Commits vs rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (pg_stat_database_xact_commit{instance=~\"$hostname\"})",
     "legendFormat": "commits"
    },
    {
     "expr": "sum by (instance) (pg_stat_database_xact_rollback{instance=~\"$hostname\"})",
     "legendFormat": "rollbacks "
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{instance=~\"$hostname\"})",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}