tls_server_config:
  cert_file: {{ salt['pillar.get']('prometheus:tls:server_certificate') }}
  key_file: {{ salt['pillar.get']('prometheus:tls:server_key') }}
  client_ca_file: {{ salt['pillar.get']('prometheus:blackbox_exporter:ca_certificate', '/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT') }}
  client_auth_type: RequireClientCert
