proxy_enabled:
  $type: boolean
  $name: Enable reverse proxy
  $default: False
  $help: Install reverse proxy for Prometheus exporters

proxy_port:
  $type: number
  $name: Reverse proxy port number
  $default: 9999
  $disabled: '!formValues.proxy_enabled'
  $required: True

node_exporter:
  $type: group
  $help: Prometheus exporter for hardware and OS metrics.

  enabled:
    $type: boolean
    $default: True

  address:
    $type: text
    $default: ':9100'

  args:
    $name: "Arguments"
    $type: text
    $help: Please refer to the documentation for available options.

apache_exporter:
  $type: group
  $help: Prometheus exporter for apache mod_status statistics.

  enabled:
    $type: boolean
    $default: False

  address:
    $type: text
    $default: ':9117'

  args:
    $name: "Arguments"
    $type: text
    $help: Please refer to the documentation for available options.

postgres_exporter:
  $type: group
  $help: Prometheus exporter for PostgreSQL server metrics.

  enabled:
    $type: boolean
    $default: False

  address:
    $type: text
    $default: ':9187'

  data_source_name:
    $type: text
    $default: postgresql://user:passwd@localhost:5432/database?sslmode=disable

  args:
    $name: "Arguments"
    $type: text
    $help: Please refer to the documentation for available options.
