proxy_enabled:
  $type: boolean
  $name: Enable reverse proxy
  $default: False
  $help: Install reverse proxy for Prometheus exporters

proxy_port:
  $type: number
  $name: Reverse proxy port number
  $default: 9999
  $disabled: '!formValues.proxy_enabled'
  $required: True

tls:
  $type: group
  $name: TLS
  $help: >
    TLS configuration. Please ensure the files are present on the minion and readable for
    the user `prometheus` before applying the highstate. Please update Prometheus formula
    configuration for targets accordingly.

  enabled:
    $type: boolean
    $default: False

  ca_certificate:
    $name: CA Certificate
    $default: /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT
    $visible: this.parent.value.enabled == true

  server_certificate:
    $name: Server Certificate
    $placeholder: /etc/ssl/server.crt
    $visible: this.parent.value.enabled == true

  server_key:
    $name: Server Key
    $placeholder: /etc/ssl/server.key
    $visible: this.parent.value.enabled == true

exporters:
  $type: group
  $help: Prometheus exporters

  node_exporter:
    $type: group
    $help: Prometheus exporter for hardware and OS metrics.

    enabled:
      $type: boolean
      $default: True

    address:
      $type: text
      $default: ':9100'

    args:
      $name: "Arguments"
      $type: text
      $help: Please refer to the documentation for available options.

  apache_exporter:
    $type: group
    $help: Prometheus exporter for apache mod_status statistics.

    enabled:
      $type: boolean
      $default: False

    address:
      $type: text
      $default: ':9117'

    args:
      $name: "Arguments"
      $type: text
      $help: Please refer to the documentation for available options.

  postgres_exporter:
    $type: group
    $help: Prometheus exporter for PostgreSQL server metrics.

    enabled:
      $type: boolean
      $default: False

    address:
      $type: text
      $default: ':9187'

    data_source_name:
      $type: text
      $default: postgresql://user:passwd@localhost:5432/database?sslmode=disable

    args:
      $name: "Arguments"
      $type: text
      $help: Please refer to the documentation for available options.
